$ANSIBLE_VAULT;1.1;AES256
37653765366135663533653631366364383662616664383033633566383833666337633239636430
6230353264323166393932343133363565346233303163370a366266386530316364303031356431
63363866333661616664616230633034373032386363653064346133396533323361353735323434
6331616161353165310a333266366539663134316564656530333530313037386437393931386262
39373564393366336235333031613863373639343436613736333136636333653533633766623264
32616662376134666134616663356362353764653132303066653862396262366632313134386265
35323237353762666534643162376236636232653166663966633434343232646237366465303063
33626461643839656236396262396135323535623239303732623364343863353066356234613863
37663334396534373031336339616463393965326438643261663663363837623731376331336631
6662346565363661326162336432656430353765306632626435
