$ANSIBLE_VAULT;1.1;AES256
63653665323963663064393537303630613133353363373130303861376363623030653066636165
3338663432356462383864356165386664613864633565340a343430303336336332326461356566
65323363373230306136366436643265396139633361633139346664353932626565323732626366
3835306234363065390a666536623464373664646137393165363765303664376364386266393961
38633030396530396236643961363535373631613630616639363636613732323232643364643334
66633066363963666335346232316434333161653532396261646438643033316461326665376562
63613962623339396330356237636261366437346337653230356161613231313132626636313033
63333162636465396132353236353064366362333834386134613537386436646463353933623534
32313233323865626135306232613364633032363539393065386236373131343138313235393635
3631666264623932326233346262643163343761663737343361
